services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
     - "1111:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fivem_tracker
      MYSQL_DATABASE: fivem_tracker
      MYSQL_USER: fivem_tracker
      MYSQL_PASSWORD: fivem_tracker
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FRONTEND_URL=https://tracker.louis.systems
      - MYSQL_HOST=mariadb
      - MYSQL_USER=fivem_tracker
      - MYSQL_PASSWORD=fivem_tracker
      - MYSQL_DATABASE=fivem_tracker
    ports:
      - "4000:4000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_URL=https://tracker.louis.sytems/
    ports:
      - "6666:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mariadb_data:
